### ISSUE TITLE
"CX_OA2C_CONFIG_PROFILE_MULTI" is unknown 

### ISSUE THREAD

**Issue by jaumealg** [SAP/abap-alv-google-upload-sheet#11]
We're getting "CX_OA2C_CONFIG_PROFILE_MULTI" is unknown  when pulling the repository
Any ideas?
We're on 740 sp22

**Comment by SAPSM** [comment]
Hi jaumealg,

I will try to clarify in which release resp. service pack of the **SAP_BASIS** software component, the exception class _CX_OA2C_CONFIG_PROFILE_MULTI_ has been introduced. As soon as I got the requested information, I will let you know in this issue report.

Kind Regards,
Sebastian

**Comment by SAPSM** [comment]
Hi jaumelag,

Unfortunately I could not determine when exactly this exception has been added to the respective SAP_BASIS _OAuth 2 API_s. It's definitely available in SAP_BASIS >= 7.50. If it's not available in your system (SAP_BASIS 7.40 SP22), I fear you have to fork the project and/or remove the respective _RAISING_ clause from the _Google Drive API_ to solve the issue. 

Kind Regards,
Sebastian
