### ISSUE TITLE
SE38: Error - SAP Certificate does not exist in PSE though Google cert installed in STRUST

### ISSUE THREAD

**Issue by Chetna20-USV** [SAP/abap-alv-google-upload-sheet#12]
se38 - error in SAP Certificate not exist in PSE though google cert installed in Strust

**Comment by larshp** [comment]
check out https://docs.abapgit.org/guide-ssl-setup.html

and try via the test program https://docs.abapgit.org/other-test-ssl.html

**Comment by Chetna20-USV** [comment]
HI , 
I am looking for Google certificate to integrate with SAP

**Comment by SAPSM** [comment]
Hi Cehtan20-USV,

I guess you are referring to the SE38 output when running report **z_googlepoc_drive_api**, right? Can you please post a screenshot of the affected certificate from transaction **STRUST**.

Kind Regards,
Sebastian
