### ISSUE TITLE
Not working when SAP system is not exposed to internet

### ISSUE THREAD

**Issue by cocquerel** [SAP/abap-alv-google-upload-sheet#4]
Hello,
the solution is not working when the SAP system is not exposed to internet as mentioned into the documentation.
it would be great if the solution would be enhanced so that we could export data to google drive from on-premise systems that are not exposed to internet.
I guess the solution would be to go through SAP Cloud Platform and SAP Cloud Connector.
Regards

**Comment by SAPSM** [comment]
Hi coquerel,

That's currently a prerequisite from Google which we cannot overcome at this point in time. But we might take your proposal into consideration.

Kind Regards
Sebastian
