### ISSUE TITLE
need a scheduler which will run the report and send it to google sheet 

### ISSUE THREAD

**Issue by Emersonanand** [SAP/abap-alv-google-upload-sheet#7]
need a scheduler which will run the report and send it to google sheet . currently i have to run the report manually  and then export to google sheet and approve..kindly help
Regards,
Emarson anand

**Comment by Emersonanand** [comment]
Any help will be be hugely appreciated

**Comment by SAPSM** [comment]
Hi Emarson,

The report in this repository is only a sample to verify that all prerequisites have been met . It checks if the necessary certificate is present and still valid, then evaluates if a valid OAuth token is available and finally tries to query the Drive API. Feel free to use the provided interfaces and classes to build up your own report. For report automation you can make use of standard SAP batch jobs to schedule a recurring execution. Does that answer your question?

Kind Regards,
Sebastian

**Comment by Emersonanand** [comment]
Dear Sebastian ,
Can you eloborate a little ? Or any example or case study how to do it
Regards,
Emarson

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by SAPSM** [comment]
Hi Emarson,

Pleas refer to the [SAP Help Portal](https://help.sap.com/viewer/index)  and search for **Batch Job**. There you will find more information on that SAP standard topic.

Kind Regards,
Sebastian

**Comment by Emersonanand** [comment]
Dear sir ,
Am not talking about standard batch job . Am talking about  scheduling job which exports reports  to google sheet. Sap india suggested git hub and you are suggesting sap?


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by SAPSM** [comment]
Hi Emarson,

I don't know what SAP India suggested. Fact is that batch jobs are a common way to automate the recurring execution of a report in an SAP backend system. They can be scheduled and repeated in nearly every possible way. Hence I recommend to get familiar with it to fulfill your task. The report to export to google sheets is not part of this sample project. The upload part can be easily created using the API to push the data to Google Drive, as provided in this repository. Regarding the export part you have to dig a bit deeper in the Web Dynpro ALV (List Viewer) or GUI ALV control. These controls provide standard export functionalities, which are unfortunately not provided as public API, hence I cannot name and recommend them officially. But for a customer (Z namespace) report, it should be fine to use them. Hope this helps. I will close this issue at this point, as it does not concern this project directly, but it is more about how to automate the upload execution with standard SAP batch job technology.

Kind Regards,
Sebastian
